package com.glance.streamline.domain.repository

enum class ApiErrors(val code: Int, val message: String){
    ERROR_UNEXPECTED_CODE(666, "ERROR_UNEXPECTED_CODE"),
    ERROR_CONVERTING_DATA_CODE(601,"ERROR_CONVERTING_DATA_CODE"),
    ERROR_INTERNET_CONNECTION_CODE(500, "ERROR_INTERNET_CONNECTION_CODE"),
    ERROR_NOT_FOUND_CODE(404, "ERROR_NOT_FOUND_CODE"),
    ERROR_UNAUTHORIZED(401, "ERROR_UNAUTHORIZED"),
    ERROR_DEVICE_ALREADY_EXIST(400,"DEVICE_ALREADY_EXIST")
}